# -*- coding: utf-8 -*-
"""assignment4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13b9RPmyRznDWr6dsVt4hp-coY-kH98hT
"""

! pip install streamlit